version: '3.9'

services:
  wiremock:
    container_name: wiremock
    image: rodolpheche/wiremock
    volumes:
      - ./mappings:/home/wiremock/mappings
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: santander
      POSTGRES_PASSWORD: cep
      POSTGRES_DB: cep
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cep
      SPRING_DATASOURCE_USERNAME: santander
      SPRING_DATASOURCE_PASSWORD: cep
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MOCK_API_BASE_URL: http://wiremock:8080/api/viacep

volumes:
  postgres_data:
